### ISSUE TITLE
Pink Outline

### ISSUE THREAD

**Issue by Kavit212** [kiraving/SegGradCAM#4]
Hi,

Is it possible to remove the pink outlines in the gradcam image. Can you please let me know which codes to modify to remove the outlines. 

Thank you very much

**Comment by kiraving** [comment]
Hi,

The outlines are quite helpful to check that you're explaining the part of the image you want to explain.
I chose pink/magenta because it is highly contrasting to the content of the Cityscape. You can easily change the color to the one that fits your data or comment the lines of code that plot the contour.

The colored contours are defined in the file: https://github.com/kiraving/SegGradCAM/blob/master/seggradcam/visualize_sgc.py

This line plots the contour on the **SegGradCAM** image
https://github.com/kiraving/SegGradCAM/blob/master/seggradcam/visualize_sgc.py#L96
This line is used if you experiment with TexturedMNIST
https://github.com/kiraving/SegGradCAM/blob/master/seggradcam/visualize_sgc.py#L102

Same lines for outlining ROIs on the GT image
https://github.com/kiraving/SegGradCAM/blob/master/seggradcam/visualize_sgc.py#L172
for TexturedMNIST
https://github.com/kiraving/SegGradCAM/blob/master/seggradcam/visualize_sgc.py#L156
